TRAIN:
  EPOCHS: 200
  BATCH_SIZE: 512
  INIT_LR: 1e-3
  WEIGHT_DECAY: 0.0
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_METHOD: EXP
  LR_DECAY_START_EPOCH: 50
  DEVICE: cuda:7

ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.9
  MIN_BETA: 0.0
  MAX_BETA: 0.85
  WARMUP_EPOCHS: 5
  ROBUST_TRAINING_START_EPOCH: 5
  ROBUST_TRAINING_LAST_EPOCH: 150
  EPS_START_EPOCH: 0
  EPS_LAST_EPOCH: 120
  MAX_EPS: 0.03137254902
  MIN_EPS: 0.03137254902
  TEST_EPS: 0.03137254902

MODEL:
  TYPE: FC
  HIDDEN_LAYERS: [100,100,100]
  ACTIVATION: bern
  DEGREE: 3
  
DATASET: cifar10

CHECKPOINT:
  DIR: experiments/cifar10/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: cifar10_FCCNb_8/255
  RUN_NAME: cifar10_robustness_eps_8/255
  DESCRIPTION: "Adversarial Robustness Benchmark for FCNNb. Networks are trained using bern-IBP and verified on 100 test images"


