TRAIN:
  EPOCHS: 300
  BATCH_SIZE: 512
  INIT_LR: 1e-2
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_METHOD: EXP
  LR_DECAY_START_EPOCH: 100
  DEVICE: cuda:5

ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.6
  MIN_BETA: 0.0
  MAX_BETA: 0.85
  WARMUP_EPOCHS: 0
  ROBUST_TRAINING_START_EPOCH: 0
  ROBUST_TRAINING_LAST_EPOCH: 100
  EPS_START_EPOCH: 0
  EPS_LAST_EPOCH: 120
  MAX_EPS: 0.03137254902
  MIN_EPS: 0.03137254902
  TEST_EPS: 0.03137254902

MODEL:
  TYPE: FC
  HIDDEN_LAYERS: [100,100,100,100,100,100,100]
  ACTIVATION: bern
  DEGREE: 10
  
DATASET: cifar10

CHECKPOINT:
  DIR: experiments/cifar10/
  LOAD: True
  PATH_TO_CKPT: "/home/hkhedr/Haitham/projects/dev/BerNN/mlruns/527035771604847429/89a5f7da37d542939e5f7e85b5fe3929/artifacts/checkpoint_best_model.pth"

EXPERIMENT:
  NAME: cifar10_FCCNc_8/255
  RUN_NAME: cifar10_robustness_eps_8/255
  DESCRIPTION: "Adversarial Robustness Benchmark for FCNNc. Networks are trained using bern-IBP and verified on 100 test images"

