TRAIN:
  EPOCHS: 300
  BATCH_SIZE: 64
  INIT_LR: 1e-3
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: Adam
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:3
  MODE: cert

TEST:
  BATCH_SIZE: 512
  MODE: adv
  IBP: True
  BERN_IBP: True
  PGD: True
  DEVICE: cuda:0

ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.1
  MAX_ALPHA: 0.9
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 50
  ROBUST_TRAINING_START_EPOCH: 50
  ROBUST_TRAINING_LAST_EPOCH: 120
  EPS_START_EPOCH: 10
  EPS_LAST_EPOCH: 10
  MAX_EPS: 0.00784313725490196
  MIN_EPS: 0.00784313725490196
  TEST_EPS: 0.00784313725490196
  TEST_EVERY_N_EPOCH : 2

MODEL:
  TYPE: CNNc
  HIDDEN_LAYERS: ""
  ACTIVATION: bern
  DEGREE: 7
  
DATASET: cifar10

CHECKPOINT:
  DIR: experiments/cifar10/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: cifar10_CNNc_2/255
  RUN_NAME: cifar10_robustness_eps_2/255
  DESCRIPTION: "Adversarial Robustness Benchmark for FCCNA. Networks are trained using bern-IBP and verified on 100 test images"