TRAIN:
  EPOCHS: 200
  BATCH_SIZE: 256
  INIT_LR: 5e-3
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:7
  MODE: cert

TEST:
  BATCH_SIZE: 512
  MODE: adv
  IBP: True
  BERN_IBP: True
  PGD: True
  DEVICE: cuda:0

ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.9
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 50
  ROBUST_TRAINING_START_EPOCH: 50
  ROBUST_TRAINING_LAST_EPOCH: 120
  EPS_START_EPOCH: 10
  EPS_LAST_EPOCH: 10
  MAX_EPS: 0.03137254902
  MIN_EPS: 0.03137254902
  TEST_EPS: 0.03137254902
  TEST_EVERY_N_EPOCH : 1

MODEL:
  TYPE: CNNc
  HIDDEN_LAYERS: ""
  ACTIVATION: bern
  DEGREE: 4
  
DATASET: cifar10

CHECKPOINT:
  DIR: experiments/cifar10/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: cifar10_CNNc_8/255
  RUN_NAME: cifar10_robustness_eps_8/255
  DESCRIPTION: "Adversarial Robustness Benchmark for FCCNA. Networks are trained using bern-IBP and verified on 100 test images"