TRAIN:
  EPOCHS: 200
  BATCH_SIZE: 512
  INIT_LR: 1e-2
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:0


ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.9
  WARMUP_EPOCHS: 5
  MIN_BETA: 0.0
  MAX_BETA: 0.7
  ROBUST_TRAINING_START_EPOCH: 5
  ROBUST_TRAINING_LAST_EPOCH: 75
  EPS_START_EPOCH: 5
  EPS_LAST_EPOCH: 120
  MAX_EPS: 0.1
  MIN_EPS: 0.1
  TEST_EPS: 0.1

MODEL:
  TYPE: FC
  HIDDEN_LAYERS: [100,100,100]
  ACTIVATION: bern
  DEGREE: 10
  
DATASET: mnist

CHECKPOINT:
  DIR: experiments/mnist/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: mnist_FCNNb_0.1
  RUN_NAME: robustness_eps_0.1
  DESCRIPTION: "Adversarial Robustness Benchmark for FCNNb. Networks are trained using bern-IBP and verified on 100 test images"


