TRAIN:
  EPOCHS: 200
  BATCH_SIZE: 128
  INIT_LR: 5e-3
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:6
  MODE: cert

TEST:
  BATCH_SIZE: 512
  MODE: adv
  IBP: True
  BERN_IBP: True
  PGD: True
  DEVICE: cuda:6

ROBUSTNESS:
  ENABLE: True
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 0.9
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 0
  ROBUST_TRAINING_START_EPOCH: 0
  ROBUST_TRAINING_LAST_EPOCH: 100
  EPS_START_EPOCH: 5
  EPS_LAST_EPOCH: 5
  MAX_EPS: 0.1
  MIN_EPS: 0.1
  TEST_EPS: 0.1
  TEST_EVERY_N_EPOCH : 1

MODEL:
  TYPE: CNNc
  HIDDEN_LAYERS: ""
  ACTIVATION: bern
  DEGREE: 2
  
DATASET: mnist

CHECKPOINT:
  DIR: experiments/mnist/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: mnist_CNNc_0.1
  RUN_NAME: mnist_CNNc_0.1
  DESCRIPTION: Adversarial Robustness Benchmark for CNNc. Networks are trained using bern-IBP and verified on 100 test images"


