TRAIN:
  EPOCHS: 100
  BATCH_SIZE: 512
  INIT_LR: 1e-3
  WEIGHT_DECAY: 0.001
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:3
  MODE: adv

TEST:
  BATCH_SIZE: 512
  MODE: adv
  IBP: True
  BERN_IBP: True
  PGD: True
  DEVICE: cuda:4

ROBUSTNESS:
  ENABLE: False
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 1.0
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 0
  ROBUST_TRAINING_START_EPOCH: 0
  ROBUST_TRAINING_LAST_EPOCH: 0
  EPS_START_EPOCH: 0
  EPS_LAST_EPOCH: 0
  MAX_EPS: 0.04
  MIN_EPS: 0.04
  TEST_EPS: 0.04
  TEST_EVERY_N_EPOCH : 5

MODEL:
  TYPE: FC
  HIDDEN_LAYERS: [20,20]
  ACTIVATION: bern
  DEGREE: 5
  
DATASET: mnist

CHECKPOINT:
  DIR: experiments_adv/mnist/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: mnist_FCNNa_0.04_adv_deg5
  RUN_NAME: robustness_eps_0.04_adv
  DESCRIPTION: "Adversarial Robustness Benchmark for FCNNa. Networks are trained using PGD and verified on 100 test images"


