TRAIN:
  EPOCHS: 100
  BATCH_SIZE: 128
  INIT_LR: 1e-3
  WEIGHT_DECAY: 0.01
  OPTIMIZER: AdamW
  LR_DECAY_RATE: 0.99
  LR_DECAY_START_EPOCH: 50
  LR_DECAY_METHOD: EXP
  DEVICE: cuda:1
  MODE: adv

# TEST:
#   BATCH_SIZE: 512
#   MODE: adv
#   IBP: True
#   BERN_IBP: False
#   PGD: False
#   DEVICE: cuda:1

ROBUSTNESS:
  ENABLE: False
  BOUNDING_METHOD: bern
  MIN_ALPHA: 0.0
  MAX_ALPHA: 1.0
  MIN_BETA: 0.0
  MAX_BETA: 0.0
  WARMUP_EPOCHS: 0
  ROBUST_TRAINING_START_EPOCH: 0
  ROBUST_TRAINING_LAST_EPOCH: 0
  EPS_START_EPOCH: 0
  EPS_LAST_EPOCH: 0
  MAX_EPS: 0.003921568627
  MIN_EPS: 0.003921568627
  TEST_EPS: 0.003921568627
  TEST_EVERY_N_EPOCH : 2

MODEL:
  TYPE: CNNb
  HIDDEN_LAYERS: ""
  ACTIVATION: bern
  DEGREE: 6
  
DATASET: tinyimagenet

CHECKPOINT:
  DIR: experiments/tinyimagenet/
  LOAD: False
  PATH_TO_CKPT: ""

EXPERIMENT:
  NAME: tinyimagenet_CNN7_clean
  RUN_NAME: tinyimagenet_CNN7_clean
  DESCRIPTION: "Training CNNa on tinyimagenet dataset"


